name: test
on: push

jobs:
  coverage:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: webfactory/ssh-agent
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.PRIVATE_SSH }}
      - name: install
        run: npm ci
